services:
  postgres:
    image: postgres:15-alpine
    container_name: medusa_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: medusa-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medusa_network

  redis:
    image: redis:7-alpine
    container_name: medusa_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - medusa_network

  medusa_server:
    image: softvalley/softvalley-hub:medusa-store-backend
    container_name: medusa_server
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: production
      MEDUSA_WORKER_MODE: server
      DISABLE_MEDUSA_ADMIN: "false"
    ports:
      - "9000:9000"
    networks:
      - medusa_network
    volumes:
      - /var/www/macrovalleyprojects/uploads:/app/.medusa/server/static      

  medusa_worker:
    image: softvalley/softvalley-hub:medusa-store-backend
    container_name: medusa_worker
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: production
      MEDUSA_WORKER_MODE: worker
      DISABLE_MEDUSA_ADMIN: "true"
    networks:
      - medusa_network

volumes:
  postgres_data:
    external: true

networks:
  medusa_network:
    driver: bridge
