version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: medusa_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: medusa-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medusa_network

  redis:
    image: redis:7-alpine
    container_name: medusa_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - medusa_network

  medusa_server:
    build: .
    container_name: medusa_server
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-store
      REDIS_URL: redis://redis:6379
      MEDUSA_WORKER_MODE: server
      DISABLE_MEDUSA_ADMIN: "false"
      # ...other production env vars
    ports:
      - "9000:9000"
    networks:
      - medusa_network

  medusa_worker:
    build: .
    container_name: medusa_worker
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-store
      REDIS_URL: redis://redis:6379
      MEDUSA_WORKER_MODE: worker
      DISABLE_MEDUSA_ADMIN: "true"
      # ...other production env vars
    networks:
      - medusa_network

volumes:
  postgres_data:
      external: true
      

networks:
  medusa_network:
    driver: bridge