# backend/.github/workflows/deploy.yml
name: Deploy Backend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository code
    - uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

    # Step 3: Build and push the Docker image
    - name: Build and Push Backend Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: softvalley/softvalley-hub:medusa-store-backend
      